name: UNOMT
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.4
  - torch=0.4.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - pandas=0.23.4
  - joblib=0.12.2
  - urllib3=1.23
  - matplotlib=3.3.4
  - requests=2.27.1
  - tqdm=4.64.1
  - numba=0.53.1
  - numpy=1.19.5 
  - astropy=4.1
  - patsy=0.5.3
  - statsmodels=0.12.2
